version: '3'

services:
  # nginx
  nginx-service:
    image: nginx:latest
    container_name: nginx-container-web
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php7.4-service
    networks:
      - pdp

  # php
  php7.4-service:
    build:
      context: ./dockerfiles/php/
    container_name: php-container-web
    ports:
      - "9001:9000"
    volumes:
      - ./app:/app
    networks:
      - pdp

  # redis
  redis-service:
      image: redis
      container_name: redis-container-web
      restart: always
      ports:
        - "6382:6379"
      volumes:
        - ./dockerfiles/redis:/data
      command: redis-server --appendonly yes
      networks:
        - pdp

networks:
  pdp:
    driver: bridge