version: '3'

networks:
  pdp:

services:
  # nginx
  nginx-service:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php7.4-service
      - mysql-service
    networks:
      - pdp

  # php
  php7.4-service:
    build:
      context: .
      dockerfile: ./dockerfiles/php/Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app
    links:
      - mysql-service
    networks:
      - pdp

  # mysql
  mysql-service:
    image: mysql:5.7
    container_name: mysql-container
    ports:
      - "33060:3306"
    volumes:
      - ./dockerfiles/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --caracter-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pdp
    networks:
      - pdp

  # redis
  redis-service:
      image: redis
      container_name: redis-container
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - /dockerfiles/redis:/data
      command: redis-server --appendonly yes